### PR TITLE
feat: separate logs on namespace and aggregate on container name

### PR DESCRIPTION
**Pull request by tmeijn**
## What
* Change the fluentbit config to separate log groups on k8s namespaces and aggregate on container name

## Why
* To better align with the k8s concept of namespace and better compartmentalize the container logs

##
**BREAKING CHANGE:** previously, all container logs from the cluster were stored in the `/aws/eks/fluentbit-cloudwatch/logs` CloudWatch Log group. With this release, cluster logs are separated by namespace and aggregated on pod level in the log streams within the namespace log group. This means that the old log group will no longer be used. To ease the transition the `log_preserve_legacy_log_group` (default: `true`) has been introduced. In a future release the old log group in Terraform may be removed.

### Before
image

### After
image

image

## Code Review

Please consider the following checklist when reviewing this Pull Request.  
More background and details [here](https://github.com/kabisa/kabisa-guide/blob/master/organization/process/code-review/README.md).

* [ ] Does the code **actually solve** the problem it was meant to solve?
* [ ] Is the code covered by **unit tests**? **Integration tests**?
* [ ] Does anything here need **documentation**? (Focus on *why*, not *what.*)
* [ ] Does any of this code deal with **privacy sensitive information** or affects **security**? Ask an additional reviewer.
* [ ] Is the code easy to **understand** and **change** in the future?
* [ ] Is the same code or concept **duplicated**? Find a balance between DRYness and readability.
* [ ] Does the code reasonably adhere to the Kabisa [**coding standards**](https://github.com/kabisa/kabisa-guide/blob/master/organization/process/code-review/README.md)?
* [ ] Be kind.

### CODE REVIEW

**Review by rhynix — APPROVED** [review]
This looks good to me. It would be good if one of the co-reviewers can also review this, because I am not very familiar with fluentbit.

**Comment by Glaaj** [comment]
Yes this is fine with me, this way we can look at logs per namespace instead of pods. Cleans up the log streams a little bit.

The only thing we don't have anymore is the management of the log groups through terraform. Wether this is a problem when there is a retention is something else.

**Comment by tmeijn** [comment]
Hey guys, thanks for the comments. I'm actually thinking to split it the logs on pod name within the namespace.

So instead of getting `app` and `nginx` it would be `constellation-backend-5f877b9c48-mpj92` and `constellation-nginx-6dc5f44965-694s5`

## Why?

The main reason is that I think aggregation on container name is too broad and has a chance of collision. Say for example you have many deployments with sidecars and you name the container `sidecar` it would aggregate all logs of those sidecars to one log stream. In addition I think it also maps slightly better to the kubernetes concepts of pods in a namespace..?

I mean, in general you just can't win with CloudWatch, but I think this would be a bit better than the previous suggestion.

**Comment by Glaaj** [comment]
Would aggregation based on deployment be an option then, that way the `sidecar` containers or other names that overlap wouldn't be that much of an issue (I think) 🤔

**Comment by obeleh** [comment]
I would agree that aggregating per Deployment makes most sense. It's the single unit of "application" in K8s. What I mean is, that's how you identify an application. I can understand the inconvenience of sidecars. But with good log filtering tools you should be able to work around this. I don't feel cloudwatch is a great place to read your logs :P 

Your change makes the logs more searchable so I like it.
Possible room for improvement:
- "logs" in the name of a log stream isn't informative ;) 
- I'm curious if the word "namespace" isn't a bit long
- We'll probably also be adding the word "deployment" maybe just dropping the words also works. But it's not a hard requirement on my side

**Review by obeleh — APPROVED** [review]
Approving to give you the room to make decisions. I don't want to block this getting merged.

**Comment by tmeijn** [comment]
Thanks both for your comments!

> Would aggregation based on deployment be an option then, that way the sidecar containers or other names that overlap wouldn't be that much of an issue (I think) thinking

> I would agree that aggregating per Deployment makes most sense. It's the single unit of "application" in K8s. What I mean is, that's how you identify an application.

image
This all the metadata that is attached the log line. I see no way to get an aggregation on deployment out of this. Let me know if you have other thoughts, but I'm inclined to go ahead with the `pod_name` proposal.

>"logs" in the name of a log stream isn't informative ;)

Agree, but that was also in the original:
image
I'll drop it.

>I'm curious if the word "namespace" isn't a bit long

We could also do `/aws/eks/constellation-dev-cluster/ns#constellation`, WDYT?

**Comment by obeleh** [comment]
I agree with your conclusion, and yes I know `/logs` was in the original ;) 
Let's go with `/aws/eks/constellation-dev-cluster/ns/constellation` ?  also fine with `#`

**Review by Glaaj — APPROVED** [review]
LGTM :shipit:!

**Pull request merged**
